from .user import UserViewset
from .rol import RolViewset
from .estudiante import EstudianteViewset
from .profesion import ProfesionViewset
from .catedratico import CatedraticoViewset
from .nivel import NivelViewset
from .grado import GradoViewset
from .seccion import SeccionViewset
from .ciclo import CicloViewset
from .curso import CursoViewset
