from .user import UserSerializer, UserReadSerializer, UserSerializerCatedratico
from .profile import ProfileSerializer, ProfileRegistroSerializer,ProfileRegistroSerializerCatedratico
from .rol import RolSerializer, RolRegistroSerializer
from .estudiante import EstudianteSerializer, EstudianteRegistroSerializer, ProfileSerializerEstudiante, UserSerializerEstudiante
from .profesion import ProfesionSerializer, ProfesionRegistroSerializer
from .catedratico import CatedraticoSerializer, CatedraticoRegistroSerializer, ProfileSerializerCatedratico, UserSerializerCatedratico
from .nivel import NivelSerializer, NivelRegistroSerializer
from .grado import GradoSerializer, GradoRegistroSerializer
from .seccion import SeccionSerializer, SeccionRegistroSerializer