from .user import UserSerializer, UserReadSerializer
from .profile import ProfileSerializer, ProfileRegistroSerializer
from .rol import RolSerializer, RolRegistroSerializer
from .estudiante import EstudianteSerializer, EstudianteRegistroSerializer, ProfileSerializerEstudiante, UserSerializerEstudiante
from .profesion import ProfesionSerializer, ProfesionRegistroSerializer
from .catedratico import CatedraticoSerializer, CatedraticoRegistroSerializer, ProfileSerializerCatedratico, UserSerializerCatedratico
